scothann/PRpracticerepo

Contributors.md

Add name PR Practice

---

Contributors.md

Add "Rasika Baskaran" and the (◕‿◕) emoji to Contributors.md

Add Rasika Baskaran to Contributors list

---

Contributors.md

Submitting Pull Request with Daniel Fontenot's name added to contributor list.

Add Daniel Fontenot to Contributors List

---

Contributors.md

Added my name to the list! (added in the middle this time, oops!)

Add bryan caples

---

Contributors.md

Added Chase Gomez to contributor list.

---

Contributors.md

I've added my name to the Contributors.md file as requested in the assignment.

Add Hrishikash Kadakia to Contributors.md

---

Contributors.md

Added Nathan Swaim to Contributor's list!

Add Nathan Swaim to Contributors list

---

Contributors.md

I added my name and a small ASCII art that represents me well, haha.

Adding jacob-vilevac to contributors list

---

Contributors.md

Added my name to contributors list

Add Josh Tan to contributors list

---

Contributors.md

Added Phil Santich to Contributors.md

Add Phil Santich to Contributors.md

---

Contributors.md

Added my name to the contributors list

Added my name to the contributors list

---

Contributors.md

Completed practice assignment!

Added Dylan Varga to Contributors.md

---

Contributors.md

Add Cameron Alsbrook to Contributors list

---

Contributors.md

Added my name to the contributors list

Add Dillon Baldwin to Contributors list

---

Contributors.md

Added contributor name

---

Contributors.md

git commit -m "Add my name to Contributors.md"

git add Contributors.md

---

Contributors.md

Here's where I would put a description of the changes I made, if I did more than just adding my name to a file.

Add Elliot Foley to Contributors list

---

Contributors.md

Add james-bray to Contributors list

---

Contributors.md

Added my name to the contributors list.

Add Jeremiah Hicks to the Contributors List

---

Contributors.md

Add Katherine Worms to Contributors List (redo - used VS first time, wanted to redo with instructions via the CLI). Updated Emoji.

Add Katherine Worms to Contributors List

---

Contributors.md

adding user JulieThurmes to list of Contributors

Add Julie Thurmes to Contributors list

---

Contributors.md

Add Alex Giger to Contributors.md

Add Alex Giger to Contributors list

---

Contributors.md

Added Name

---

Contributors.md

Add my name to Contributors.md

Added name to Contributors.md

---

Contributors.md

Add Allison-Karlis to Contributors list

---

Contributors.md

added Noah Strong to Contributors list

Added Noah Strong to Contributors list

---

Contributors.md

Pull request for PR Practice assignment. It's a little unclear, but the two objects on the sides of my ASCII art are peace signs.

knowltod PR Practice

---

Contributors.md

Hello, this PR adds my name and favorite emoji to the contributors file, per the practice assignment. 
Please let me know if you have any issues. 
Thanks!

Add Benjamin Liden-Sellers to contributors file

---

Contributors.md

Update Contributors.md millemme

---

Contributors.md

add Liam Clark to Contributors

---

Contributors.md

Adding my name to the Contributors list.

Add cory-apperson to Contributors list

---

Contributors.md

adding my name to the contributors list

Add Jane Brusilovsky to Contributors list

---

Contributors.md

added dominic fantauzzo to list with glasses person emoji 6_6

Add Dominic Fantauzzo to Contributors list

---

Contributors.md

Add duong-tran to Contributors list

---

Contributors.md

I am adding my name to contributors list

Add Bran Cowan to contributors list

---

Contributors.md

Added Kevin Hernández to Contributors.md

Add Kevin Hernandez to Contributors list

---

Contributors.md

Add Cody Ray to Contributors list

---

Contributors.md

For completion of "PR Practice".

Add Andrew Ketola to Contributors list

---

Contributors.md

Add edward-leyva to Contributors list

---

Contributors.md

Added Derek Westjohn and guitar emoji :)

added Derek Westjohn to Contributors List

---

Contributors.md

Add Zachary Hogan to contributors list

Add Zachary Hogan to Contributors list

---

Contributors.md

Add Nicholas Pettus to Contributors list

Add Nicholas Pettus to Contributors list

---

Contributors.md

Added my name and emoticon to contributors.

Add Jessica Vasilenko to Contributors list

---

Contributors.md

Added only My name to the list

Add Shubhank Gyawali to Contributors list

---

Contributors.md

Added Maddi Spawn to the file! :)

Added my name to Contributors.md

---

Contributors.md

Add vaughn-blandy to Contributors list

---

Contributors.md

Add Kristan Koeplin to Contributors list

---

Contributors.md

Pr Practice assignment for CS 464 of cloning and pushing a new branch from personal git clone of a OSS project.

Add Ashton Haviland to Contributors list

---

Contributors.md

Hello, I added myself to the contributor list.

Add Alexa Herrera to Contributors list

---

Contributors.md

Very simple addition of my name to the list of contributors as per the README instructions.

Add Alex Ngo to Contributors list

---

Contributors.md

pull request for PR practice assignment

Add Alexander Ngo to Contributor List

---

Contributors.md

Updated file with my name

---

Contributors.md

PR Practice assignment. Add Jane Lynn to Contributors List.

Add Jane Lynn to Contributors List

---

Contributors.md

Adds Anthony Abruzzini (hey that's me) as well as orangutan emoticon (credit:  Richard Zimmerman of redapes.org) to contributors.md

Add Anthony Abruzzini to Contributors list

---

Contributors.md

This pull request is to add "Gizem Kavas" to Contributors List

Add Gizem Kavas to Contributors List

---

Contributors.md

Add Yahir Gonzalez to Contributors list

---

Contributors.md

I added my name in Contributors.md.

Add Shinji Nobuhara to Contributors list

---

Contributors.md

Added "Cameron Rice ‼️" to Contributors.md

Add Cameron Rice to Contributors list

---

Contributors.md

Add Tran Cong Son Nguyen to Contributors.md

---

Contributors.md

Add Sean Brady to Contributors list

Add Sean Brady to Contributors list

---

Contributors.md

Add Noshin Raisa to Contributors list

Add Noshin Raisa to Contributors list

---

Contributors.md

Added my name to Contributors list  
I've added "Aadil Ali :p" to the list of contributors. This is my first pull request for CS 464, showing that I can use GitHub's basic features. This exercise helps me learn how to contribute to an open source project, and this PR demonstrates the basic skills of forking a repository, creating a branch, making changes, and submitting a pull request.

Aadil Ali OSS Contributions

---

Contributors.md

Add Theo Sweilem to Contributors List

Add Theo Sweilem to Contributors List

---

Contributors.md

Adding my name to the contributors list as per the assignment instructions!

Add adam-jennings to Contributors list

---

Contributors.md

Added Katrine Chow to the list!

Add Katrine Chow to Contributors list

---

Contributors.md

Add Will Garrison to Contributers.md

---

Contributors.md

This is my github pull request demo for 464 Open Source on April 15 2025 - Spring Term.

Added Andy (Truongan) Vo to contributors list

---

Contributors.md

This is the submission for Kyler Lawbaugh in CS464 for the PR Practice!

Add kyler-lawbaugh to Contributors list

---

Contributors.md

Add Dylan Freshman to Contributors List

Add Dylan Freshman to Contributors List

---

Contributors.md

Adding my name to the Contributors file as part of the integration-manager workflow practice assignment for class. 🚀

Add Blayton Vidrine to Contributors

---

Contributors.md

Add Brian Anderson to Contributors list

---

Contributors.md

Completing PR Practice assignment for Oregon State University, CS464- Open Source Software.

Add Erik Christiansen to the Contributors list

---

Contributors.md

Adding Jack Armstrong to Contributors.md

Add Jack Armstrong to Contributors list

---

Contributors.md

Added Natasha Pavelek to Contributors list

---

Contributors.md

Adding Nathan Shadnik to the Contributor's list.

Add Nathan Shadnik to Contributors list

---

Contributors.md

Please add Gavin Bennett, thank you!

Added Gavin Bennett to Contributors list

---

Contributors.md

Hello! This is Hannah Le from CS464, and I'm requesting a pull request after adding my name to the Contributors.md file Thank you!

Add Hannah Le to Contributors list

---

Contributors.md

Added "Nira Patel" to line 14 of `Contributors.md`.

Add Nira Patel to Contributors list

---

Contributors.md

Add Kevin Mai to Contributors list

Add Kevin Mai to Contributors list

---

Contributors.md

Added my name to Contributors.md

Added Benny Chen to Contributors list

---

Contributors.md

Add Cooper Thompson to Contributors list

---

Contributors.md

Added my name as requested for the PR Practice assignment

Add Raiden Lazaro to Contributors

---

Contributors.md

Practice pull request adding my name to the Contributors.md file.

Added Charles Holz to Contributors list

---

Contributors.md

Added Derek R. Greene to contributors.md file

Added Derek R. Greene to contributors

---

Contributors.md

Adding my name to Contributors list

Add Kiara Gomez to Contributors list

---

Contributors.md

This is a weird request just to be considered for the apartment on Craiglist, but hopefully submitting my name here gets me considered? Is it just first and last? What's the deal? Why are there so many applicants for this place?

Add Jacob Pham to Contributors list

---

Contributors.md

Add Andrew Sullivan to Contributors list

Add Andrew Sullivan to Contributors list

---

Contributors.md

Add Sage Morgillo to Contributors list

---

Contributors.md

Add Ryan Spencer to Contributors list for PR Practice assignment.

Add Ryan Spencer to Contributors list

---

Contributors.md

Add Aidan Lusk to Contributors list

---

Contributors.md

Add Cole-Allen to Contributors list

---

Contributors.md

I've just added my name into the contributors list (Van To ^~^)

Add Van To to Contributors list

---

Contributors.md

Add your-name to Contributors list

---

Contributors.md

Added myself Jesus Martienz to the list.

Added myself Jesus Martinez to the contributors list

---

Contributors.md

added my name for the assignment

Add Raul Preciado to Contributors list

---

Contributors.md

Added my name to contributors list

Add Payton Carter to Contributors list

---

Contributors.md

Added Madonna Matta :P  to Contributors.md

Add Madonna Matta to Contributors list

---

Contributors.md

adding my name part of PR practice

Add Mikaella Brewer to Contributors list

---

Contributors.md

Added my name to the Contributors.md file

Add Eduardo Camacho to Contributors list
